#!/usr/bin/env bash

set -e

nix-build -A update-nix-fetchgit -o updater

# int(egration)
./updater/bin/update-nix-fetchgit nix/hnix.nix --rev refs/heads/int

# storepath
./updater/bin/update-nix-fetchgit nix/hnix-store.nix --rev refs/heads/storepath

# poly derivation
./updater/bin/update-nix-fetchgit nix/nix-diff.nix --rev refs/heads/poly

# GHC 883 fixes and other bits
./updater/bin/update-nix-fetchgit nix/update-nix-fetchgit.nix --rev refs/heads/fixes

# master
./updater/bin/update-nix-fetchgit nix/nix-narinfo.nix
./updater/bin/update-nix-fetchgit nix/update-nix-file.nix
