#!/usr/bin/env bash

./update_sorki
go () { ./updater/bin/update-nix-fetchgit $*; }


# temp/octo
go nix/hnix.nix --rev refs/heads/temp/octo

# temp/octo
go nix/hnix-store.nix --rev refs/heads/temp/octo
