#!/usr/bin/env bash

set -e

test -d updater || nix-build -A update-nix-fetchgit -o updater
go () { ./updater/bin/update-nix-fetchgit $*; }

# int(egration)
go nix/hnix.nix --rev refs/heads/int

# storepath
# https://github.com/haskell-nix/hnix-store/pull/59/
go nix/hnix-store.nix --rev refs/heads/storepath

# GHC 883 fixes and other bits
# https://github.com/expipiplus1/update-nix-fetchgit
go nix/update-nix-fetchgit.nix --rev refs/heads/fixes

# master
go nix/nix-narinfo.nix
go nix/update-nix-file.nix
go nix/hnixbot.nix
go nix/hnix-store-experiments.nix

# upstream
go nix/nix-diff.nix
go nix/nix-derivation.nix
